young:
  # 开发者应该设置成自己的wx相关信息
  wx:
    app-id: wxcd789dd2321424b6
    app-secret: 9282eb321d3c9ece3c06857e2c54be8e
    mch-id: 1538666666
    mch-key: 1538xxxxxx-1538xxxxxx-1538xxxxxx
    notify-url: https://test.dtsshop.com/demo/order/dtsNotify
    # 商户证书文件路径
    # 请参考“商户证书”一节 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3
    key-path: xxxxx

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置,邮箱一般用于接收业务通知例如收到新的订单，sendto 定义邮件接收者，通常为商城运营人员
      enable: true
      host: smtp.163.com
      username: yqzzyg@163.com
      password: TOLTIFEAELFYBSLE
      sendfrom: yqzzyg@163.com
      sendto: 452737801@qq.com

    # 短消息模版通知配置
    # 短信息用于通知客户，例如发货短信通知，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    sms:
      enable: false
      appid: 1400286323
      appkey: 223123sade14c129c4ce9a30b5f90ad2c
      template:
        - name: paySucceed
          templateId: 112233
        - name: captcha
          templateId: 112233
        - name: ship
          templateId: 112233
        - name: refund
          templateId: 112233
    AliyunSms:
      enable: true
      accessKeyId: LTAI4G9JxU1qicuVDrwpybDM
      accessSecret: bEWHuag9MBEK2cyAzy6HXdevWXAwjO
      domain: dysmsapi.aliyuncs.com
      version: 2017-05-25
      action: SendSms
      regionId: cn-hangzhou
      SignName: mall商城
      template:
        - name: refund
          templateId: SMS_176537411
    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: true
      template:
        - name: paySucceed
          templateId: sirUcgTAIQfoIxxxxxx
        - name: captcha
          templateId: OfBkXh7UILpsDkcxxxxxx
        - name: ship
          templateId: dqTuWzrmL_wwK-SJsxxxxxx
        - name: applyRefund
          templateId: lzPHltMpUOiBol7i2Yxxxxxx
        - name: refund
          templateId: NDy6EpPuu2C9NMUxxxxxx

  # 快鸟物流查询配置
  express:
    enable: true
    appId: "xxxxxx"
    appKey: "xxxxxx"
    vendors:
      - code: "HTKY"
        name: "百世快递"
      - code: "YZBK"
        name: "邮政国内标快"
      - code: "ZTO"
        name: "中通快递"
      - code: "YTO"
        name: "圆通速递"
      - code: "YD"
        name: "韵达速递"
      - code: "YZPY"
        name: "邮政快递包裹"
      - code: "EMS"
        name: "EMS"
      - code: "DBL"
        name: "德邦快递"
      - code: "FAST"
        name: "快捷快递"
      - code: "ZJS"
        name: "宅急送"
      - code: "TNT"
        name: "TNT快递"
      - code: "UPS"
        name: "UPS"
      - code: "DHL"
        name: "DHL"
      - code: "FEDEX"
        name: "FEDEX联邦(国内件)"
      - code: "FEDEX_GJ"
        name: "FEDEX联邦(国际件)"

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu、MinIO
    active: minIO
    # 本地对象存储配置信息
    local:
      storagePath: ./mall/storage/
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: /mall/image/
    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-beijing.aliyuncs.com
      accessKeyId: LTAI4G9JxU1qicuVDrwpybDM
      accessKeySecret: bEWHuag9MBEK2cyAzy6HXdevWXAwjO
      bucketName: young-mall
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: AKIDKSJuHQz3UiiRv9sKWT7e4HG2buz2ZLfk
      secretKey: zjDTnshT0PbZImbFepmSyDCvToRpxqVu
      region: ap-nanjing
      bucketName: young-mall-1300446798
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://dtsshop.wx.clouddn.com
      accessKey: 111111
      secretKey: xxxxxx
      bucketName: dts
    # Minio
    MinIO:
      accessKey: admin #访问的key
      secretKey: admin123456 #访问的秘钥
      endpoint: http://106.54.139.18:9000 #MinIO服务所在地址
      bucketName: young-mall
pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql
