spring:
  datasource:
    url: jdbc:mysql://localhost:3306/young-shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yqz12358
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
#    host: 106.54.139.18
#    password: redis12358
#    database: 8
#    port: 6379
#    timeout: 3000
#  redisTemplate使用，可用于普通缓存
#  redisson使用，redisson分布式锁
    redisson:
      config: classpath:redisson.yml

