server:
  port: 8081
  servlet:
    context-path: /demo

spring:
  application:
    name: young-mall-wx
  profiles:
    active: dev,common #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:com/young/db/dao/*.xml
    - classpath:com/young/db/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: young-mall-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头
redis:
  key:
    admin: 'mall:admin'
    resourceList: 'mall:List'
  expire:
    common: 86400 # 24小时
